# Generated by Django 3.2.9 on 2021-12-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0002_auto_20211207_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='size',
            field=models.CharField(choices=[('L', 'LARGE'), ('S', 'SMALL'), ('M', 'MEDIUM'), ('XL', 'EXTRA LARGE')], default='S', max_length=2),
        ),
    ]
